services:
  - type: web
    name: fsl-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      PYTHON_VERSION: 3.10.13
